# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  Compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml


  Test:
    needs: Compile
    runs-on: ubuntu-latest

    steps:
    - run: tree
    - run: mkdir staging && cp *.jar /staging
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: staging

  Assemble:
    needs: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: staging

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: staging
