# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  
#  pull_request:
#    branches: [ main ]

jobs:
  Compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - run: sudo mkdir staging && sudo cp ./target/*.jar ./staging
    - uses: actions/upload-artifact@v2
      with:
        name: buildJar
        path: staging


  Test:
    needs: Compile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: mvn test
    - run: ls -al -R
    - run: tree ./target
    - run: sudo cp -R ./target/surefire-reports/ ./staging
    - uses: actions/upload-artifact@v2
      with:
        name: testReport
        path: staging

  Assemble:
    needs: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          path: staging

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: staging/buildJar/
#       - run: mvn exec:java -Dexec.mainClass="Game"
#      - run: java -jar ./buildJar/lab_4-1.0-SNAPSHOT.jar

  Release:
#       needs: Assemble
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/download-artifact@v2
          with:
            path: staging
        - name: Release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: staging/buildJar/lab_4-1.0-SNAPSHOT.jar
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
